package utils;

/**
 * Loads the configuration values used by the analyzation process
 */
public class RuleKeys {

	private RuleKeys() {

	}
	// Rule Definitions

	public static final String ENTITY_DEFINITION = "ENTITY_DEFINITION";
	public static final String ENTITY_COLUMN_DEFINITION_FIELD = "ENTITY_COLUMN_DEFINITION_FIELD";
	public static final String ENTITY_COLUMN_DEFINITION_METHOD = "ENTITY_COLUMN_DEFINITION_METHOD";

	public static final String RELATIONSHIP_PRIORITY = "RELATIONSHIP_PRIORITIES";
	public static final String AGGREGATION_DEFINITION = "AGGREGATION_DEFINITION";
	public static final String COMPOSITION_DEFINITION = "COMPOSITION_DEFINITION";
	public static final String INHERITENCE_DEFINITION = "INHERITENCE_DEFINITION";

	public static final String USE_CASE_DEFINITION_CLASS = "USE_CASE_DEFINITION_CLASS";
	public static final String USE_CASE_DEFINITION_METHOD = "USE_CASE_DEFINITION_METHOD";

	public static final String USE_CASE_DEFINITION_READ_SET_OPERATION = "USE_CASE_DEFINITION_READ_SET_OPERATION";
	public static final String USE_CASE_DEFINITION_READ_OPERATION_PRIO = "USE_CASE_DEFINITION_READ_OPERATION_PRIO";
	public static final String USE_CASE_DEFINITION_READ_CONDITION_PRIO = "USE_CASE_DEFINITION_READ_CONDITION_PRIO";
	public static final String USE_CASE_DEFINITION_READ_VALUE_PRIO = "USE_CASE_DEFINITION_READ_VALUE_PRIO";

	public static final String USE_CASE_DEFINITION_WRITE_SET_OPERATION = "USE_CASE_DEFINITION_WRITE_SET_OPERATION";
	public static final String USE_CASE_DEFINITION_WRITE_OPERATION_PRIO = "USE_CASE_DEFINITION_WRITE_OPERATION_PRIO";
	public static final String USE_CASE_DEFINITION_WRITE_CONDITION_PRIO = "USE_CASE_DEFINITION_WRITE_CONDITION_PRIO";
	public static final String USE_CASE_DEFINITION_WRITE_VALUE_PRIO = "USE_CASE_DEFINITION_WRITE_VALUE_PRIO";
}
